libvirt:
  config:
    source: "dmacvicar/libvirt"
    version: "0.6.12"

iac:
  name: "okd"
  domain: "kube.ac"
  providers:
  - name: "ivy"
    type: "libvirt"
    config: "qemu+ssh://root@192.168.0.3/system"
  pools:
  - name: "default"
    path: "/virtualki"
#  networks:
#  - name: "main"
#    bridge: "br0"
  volumes:
  - name: ubuntu-jammy
    source: "http://192.168.0.2:8765/jammy-server-cloudimg-amd64-disk-kvm.img"
    format: "qcow2"
    pool: "default"
  hosts:
    s:
      count: 1
      roles:
      - openshift
      provider:
        name: ivy
      disks:
      - name: "root"
        size: "53687091200"
        pool: "default"
        base_volume: "ubuntu-jammy"
      networks:
#      - name: "main"
      - bridge: "br0"
        mac_priefix: "44:8a:5b:00:07"
      resources:
        cpu: 7
        mem: 14000

