---
# tasks file for openshift
- ansible.builtin.include_role:
    name: base

- name: create group libvirt
  ansible.builtin.group:
    name: libvirt

- name: sudoers for okd
  community.general.sudoers:
    name: okd
    state: present
    user: okd
    commands: ALL
    nopassword: true

- name: create user okd
  ansible.builtin.user:
    name: okd
    groups: 
    - sudo
    - libvirt
    shell: /bin/bash
    password: "$y$j9T$C9PtMrU3Ht2H3FM02RgvM.$j.EQzLkPUG/C7QDh1k8NfWqboaO310C/M7a/TDD911A" #pass: okd

- name: okd's .bash_profile
  ansible.builtin.template:
    src: okd-bash_profile
    dest: /home/okd/.bash_profile
    mode: 0600
    owner: okd

- name: download okd files
  ansible.builtin.get_url:
    url: "{{ crc_url }}"
    dest: "/home/okd/{{ crc_url.split('/')[-1] }}"
    mode: '0666'

- name: unpack okd files
  ansible.builtin.unarchive:
    src: "/home/okd/{{ item }}"
    dest: "/usr/local/bin"
    include: "*/crc"
    remote_src: yes
    mode: 0777
    extra_opts: 
    - --wildcards
    - "--strip-components=1"
  with_items:
  - "{{ crc_url.split('/')[-1] }}"

- name: enable linger
  ansible.builtin.command: loginctl enable-linger okd

- name: upload pullSecret
  ansible.builtin.copy:
    src: pullSecret
    dest: /home/okd/pullSecret
  become: true
  become_method: sudo
  become_user: okd

- name: run crc
  ansible.builtin.shell: >
    cd ${HOME} && source .bash_profile
    && crc config set consent-telemetry no
    && crc config set network-mode user
    && crc config set pull-secret-file /home/okd/pullSecret
    && crc setup 2>&1 | tee crc.log
  args:
    executable: /bin/bash
  become: true
  become_method: sudo
  become_user: okd

- name: create /home/okd/.kube directory
  ansible.builtin.file:
    path: /home/okd/.kube
    state: directory
  become: true
  become_method: sudo
  become_user: okd

- name: locate kubeconfig
  ansible.builtin.find:
    paths: /home/okd/.crc/cache
    recurse: yes
    pattern: kubeconfig
  register: kubeconfig_location

- name: print kubeconfig location
  ansible.builtin.debug:
    var: item['path']
  with_items: "{{ kubeconfig_location.files }}"
  loop_control:
    label: "{{ item['path'] }}"

#- name: fail when more than one kubeconfig found
#  fail:
#    msg: more than one kubeconfig found
#  when: kubeconfig_locount.files|count > 1

- name: link kubeconfig
  ansible.builtin.file:
    src: "{{ kubeconfig_location.files[0].path }}"
    dest: /home/okd/.kube/config
    state: link
  become: true
  become_method: sudo
  become_user: okd

- name: download odo
  ansible.builtin.get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64.tar.gz"
    dest: "/home/okd/odo-linux-amd64.tar.gz"
    owner: okd
    mode: 0600

- name: unpack odo
  ansible.builtin.unarchive:
    src: "/home/okd/odo-linux-amd64.tar.gz"
    dest: "/usr/local/bin"
    include: "odo"
    remote_src: yes
    mode: 0777

