- hosts: all
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: remove packages
    apt:
      pkg: ['eject','nano','xauth']
      state: absent
  - name: autoremove
    apt:
      autoremove: yes
  - name: install packages
    apt:
      pkg: ['qemu-kvm','libvirt-daemon-system','bridge-utils']
      state: latest
  - name: upload bridge config
    template:
      src: netplan-bridge.j2
      dest: /etc/netplan/00-installer-config.yaml
      owner: root
      backup: yes
    notify: restart netplan
  - name: apparmor profile for libvirt
    lineinfile:
      dest: /etc/apparmor.d/libvirt/TEMPLATE.qemu
      insertafter: "#include <abstractions/libvirt-qemu>"
      line: "  /virtualki/** rkw,"
      state: present
  - name: disable suspend on lid close
    lineinfile:
      dest: /etc/systemd/logind.conf
      line: "HandleLidSwitch=lock"
      regexp: "HandleLidSwitch="
      state: present
    notify: restart logind
  - name: set dns
    lineinfile:
      dest: /etc/systemd/resolved.conf
      line: "DNS=192.168.0.2"
      regexp: "DNS="
      state: present
    notify: restart resolved
  - name: sshd password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: "PasswordAuthentication yes"
      regexp: "(^|^#)PasswordAuthentication"
    notify: restart sshd

  handlers:
  - name: restart netplan
    command: netplan apply
    async: 100
    poll: 0
  - name: restart logind
    systemd:
      name: systemd-logind.service
      state: restarted
  - name: restart resolved
    systemd:
      name: systemd-resolved.service
      state: restarted
  - name: restart sshd
    systemd:
      name: sshd
      state: restarted

