- hosts: all
  tasks:
  - name: set root password to root
    user:
      name: root
      password: $6$iG.fK9HGq5UC7PsG$sxUxXYhWcokTKgp2cOrYhuJ0P4UbefzgkU9Nfk1MHgbJb6LqesquSx0HtH2PcaRmmobL6rn2bWEDnh1/DZ7UP.
  - name: set keymap
    lineinfile:
      path: /etc/default/keyboard
      regex: "XKBLAYOUT="
      line: "XKBLAYOUT=\"pl\""
  - name: Set timezone to Europe/Zurich
    community.general.timezone:
      name: Europe/Zurich
  #- name: Set 24h date
  #  command: localectl set-locale LC_TIME="en_GB.UTF-8"
  #  changed_when: False
  - name: remove unneeded packages
    apt:
      pkg: ['eject','nano','xauth']
      state: absent
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: autoremove
    apt:
      autoremove: yes
  - name: install packages
    apt:
      pkg: ['vim','git','ncdu', 'systemd-cron','dnsutils']
      state: latest
  - name: disable suspend on lid close
    lineinfile:
      dest: /etc/systemd/logind.conf
      line: "HandleLidSwitch=lock"
      regexp: "HandleLidSwitch="
      state: present
    notify: restart logind
  - name: set dns
    lineinfile:
      dest: /etc/systemd/resolved.conf
      line: "DNS=192.168.0.2"
      regexp: "DNS="
      state: present
    notify: restart resolved
  - name: sshd password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: "PasswordAuthentication yes"
      regexp: "(^|^#)PasswordAuthentication"
    notify: restart sshd
  - name: disable ssh fingerprint check
    lineinfile:
      dest: /etc/ssh/ssh_config
      line: StrictHostKeyChecking no
      regexp: StrictHostKeyChecking
      state: present
  - name: .bash_profile
    get_url:
      url: 'https://raw.githubusercontent.com/toleksa/configs/main/.bash_profile'
      dest: '/root/.bash_profile'
      mode: '0700'
  - name: .bashrc
    get_url:
      url: 'https://raw.githubusercontent.com/toleksa/configs/main/.bashrc'
      dest: '/root/.bashrc'
      mode: '0700'
  - name: .vimrc
    get_url:
      url: 'https://raw.githubusercontent.com/toleksa/configs/main/.vimrc'
      dest: '/root/.vimrc'
      mode: '0700'
  - name: /etc/issue
    copy:
      dest: /etc/issue
      content: |
        Ubuntu 22.04 LTS \n \l
        
        \4


      mode: '0644'
  - name: remove /etc/update-motd.d/
    file:
      path: /etc/update-motd.d/
      state: absent
  - name: create /etc/cron.hourly
    file:
      path: /etc/cron.hourly
      state: directory
      mode: '0755'
  - name: get dns-update.sh
    get_url:
      url: 'http://192.168.0.2:8765/dns-update.sh'
      dest: '/etc/cron.hourly/dns-update.sh'
      mode: '0700'
    notify: update dns
  - name: crontab dns-update
    cron:
      name: dns-update.sh
      special_time: reboot
      job: '/etc/cron.hourly/dns-update.sh'

  handlers:
  - name: restart logind
    systemd:
      name: systemd-logind.service
      state: restarted
  - name: restart resolved
    systemd:
      name: systemd-resolved.service
      state: restarted
  - name: restart sshd
    systemd:
      name: sshd
      state: restarted
  - name: update dns
    shell: /etc/cron.hourly/dns-update.sh
