---
# tasks file for argocd/apps.yaml

- name: upload app yamls
  template:
    src: "apps/{{ item }}"
    dest: "/{{ item }}"
  with_items: "{{ hostvars.localhost.iac.argocd.apps }}"
  when: "hostvars.localhost.iac.argocd.apps is defined"

- block:
  - name: deploy apps
    kubernetes.core.k8s:
      state: present
      src: "/{{ item }}"
    with_items: "{{ hostvars.localhost.iac.argocd.apps }}"
    when: "hostvars.localhost.iac.argocd.apps is defined"
  run_once: true

- name: clone kube-apps repo
  ansible.builtin.git:
    repo: 'https://github.com/toleksa/kube-apps.git'
    dest: /root/kube-apps
    version: HEAD

