---
# tasks file for rke2
- name: get rke2 installer
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2.sh
    mode: 0700

- name: install rke2
  ansible.builtin.command: |
    /tmp/rke2.sh
  args:
    creates: /var/lib/rancher/rke2/bin/kubectl

- name: start rke2
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started
    enabled: yes

- name: .bashrc variables
  lineinfile:
    path: /root/.bashrc
    line: "{{ item }}"
  with_items:
  - "export PATH=$PATH:/var/lib/rancher/rke2/bin"
  - "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml"

