---
# tasks file for rke2
- name: install python3-kubernetes
  apt:
    pkg: python3-kubernetes
    state: present

- name: get rke2 installer
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2.sh
    mode: 0700

- name: install rke2
  ansible.builtin.command: |
    /tmp/rke2.sh
  args:
    creates: /var/lib/rancher/rke2/bin/kubectl

- name: start rke2
  ansible.builtin.systemd:
    name: rke2-server.service
    state: started
    enabled: yes

- name: Set ingress as LoadBalancer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-ingress-nginx
        namespace: kube-system
      spec:
        valuesContent: |-
          controller:
            publishService:
              enabled: true
              pathOverride: kube-system/rke2-ingress-nginx-controller
            service:
              enabled: true
              type: LoadBalancer

- name: .bash_kube
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/toleksa/configs/main/.bash_kube'
    dest: '/root/.bash_kube'
    mode: '0700'

- name: add .bash_kube to .bashrc
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    block: |
      if [ -f ~/.bash_kube ]; then
          . ~/.bash_kube
      fi

