apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-main
  namespace: argocd
  annotations:                                                                                                                                                                             
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true 
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/kube-system'
    targetRevision: HEAD
    path: 'argocd'
    helm:
      values: |
        domain: "{{ hostvars.localhost.iac.name }}.{{ hostvars.localhost.iac.domain|default(default.iac.domain) }}"

        longhorn:
          defaultClassReplicaCount: 1
          ingress:
            enabled: true

        argocd:
          dex:
            enabled: false
          server:
            ingress:
              enabled: true
              https: true
            config:
              repositories: |
                - type: helm
                  name: stable
                  url: https://charts.helm.sh/stable
                - type: helm
                  name: argo-cd
                  url: https://argoproj.github.io/argo-helm
        monitoring:
          enabled: {{ hostvars.localhost.iac.argocd.monitoring.enabled|default('false') }}
        externaldns:
          enabled: {{ hostvars.localhost.iac.argocd.dns.enabled|default('false') }}
          rfc2136:
            host: "{{ hostvars.localhost.iac.argocd.dns.host|default() }}"
            zone: "{{ hostvars.localhost.iac.argocd.dns.zone|default() }}"
            tsigSecret: "{{ hostvars.localhost.iac.argocd.dns.secret|default() }}"
          metrics: {{ hostvars.localhost.iac.argocd.dns.metrics|default('false') }}
          sources: {{ hostvars.localhost.iac.argocd.dns.sources|default() }}

        metallb:
          pools:
          - name: default
            protocol: layer2
            addresses:
            - "{{ hostvars.localhost.iac.argocd.metallb.addresses|default(ansible_default_ipv4.address + '-' + ansible_default_ipv4.address) }}"
            avoid-buggy-ips: true

        elk:
          enabled: {{ hostvars.localhost.iac.argocd.elk.enabled|default('false') }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
