libvirt:
  config:
    source: "dmacvicar/libvirt"
    version: "0.6.12"

iac:
  name: "c3"
  domain: "kube.ac"
  providers:
  - name: "virtbox"
    type: "libvirt"
    config: "qemu+ssh://root@192.168.0.4/system"
  - name: "ivy"
    type: "libvirt"
    config: "qemu+ssh://root@192.168.0.3/system"
  - name: "virtualbox"
    type: "vbox"
    config: "vbox://invalid_addr/hehe"
  pools:
  - name: "default"
    path: "/virtualki"
  networks:
  - name: "main"
    bridge: "br0"
  volumes:
  - name: ubuntu-jammy
    source: "http://192.168.0.2:8765/jammy-server-cloudimg-amd64-disk-kvm.img"
    format: "qcow2"
    pool: "default"
  argocd:
    dns:
      #enabled: false
      #host: 127.0.0.1
      #zone: "example.com"
      #secret: "secret"
      enabled: true
      host: 192.168.0.2
      zone: "kube.ac"
      secret: "{{ lookup('ansible.builtin.env', 'DNS_KEY')|default() }}"
    metallb:
      #addresses: "127.0.0.1"
  rke2:
    join_token: multi-123456
  hosts:
    s:
      count: 3
      roles:
      - argocd
      provider:
        name: virtbox
      disks:
      - name: "root"
        size: "53687091200"
        pool: "default"
        base_volume: "ubuntu-jammy"
      networks:
      - name: "main"
        mac_prefix: "44:8a:5b:00:06"
      resources:
        cpu: 3
        mem: 4000
      user_data_pool: "default"
      user_data:
        prefer_fqdn_over_hostname: true
        ssh_pwauth: True
        chpasswd:
          list: root:root
          expire: False

        users:
          - name: root
            ssh_import_id:
              - gh:toleksa

        packages:
          - qemu-guest-agent

        runcmd:
          - systemctl start qemu-guest-agent
    w:
      count: 3
      roles:
      - argocd
      - rke2_worker
      provider:
        name: ivy
      disks:
      - name: "root"
        size: "53687091200"
        pool: "default"
        base_volume: "ubuntu-jammy"
      networks:
      - name: "main"
        mac_prefix: "44:8a:5b:00:16"
      resources:
        cpu: 3
        mem: 4000
      user_data_pool: "default"
      user_data:
        prefer_fqdn_over_hostname: true
        ssh_pwauth: True
        chpasswd:
          list: root:root
          expire: False

        users:
          - name: root
            ssh_import_id:
              - gh:toleksa

        packages:
          - qemu-guest-agent

        runcmd:
          - systemctl start qemu-guest-agent
