---
# handlers file for base
- name: restart_kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
    enabled: yes

- name: restart_nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: restart_apache2
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: restart_elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart_logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes

- name: restart_filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: restart_metricbeat
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
    enabled: yes

