---
# handlers file for base
- name: restart_kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
    enabled: yes

- name: restart_nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: restart_apache2
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: restart_elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart_logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes

- name: restart_filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: restart_metricbeat
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted
    enabled: yes

#TODO: this -> dirty workaround
- name: setup_filebeat
  ansible.builtin.shell: >
    filebeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] -E setup.kibana.host=localhost:5601
    && filebeat setup -e --pipelines --modules system -M "system.syslog.enabled=true" -M "system.auth.enabled=true"
    && filebeat setup -e --pipelines --modules nginx -M "nginx.access.enabled=true" -M "nginx.error.enabled=true"

- name: setup_metricbeat
  ansible.builtin.shell: >
    metricbeat setup -e -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] -E setup.kibana.host=localhost:5601

