apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-main
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/kube-system'
    targetRevision: HEAD
    path: 'argocd'
    helm:
      values: |
        domain: "{{ hostvars.localhost.iac.name }}.{{ hostvars.localhost.iac.domain|default('example.com') }}"

        longhorn:
          defaultClassReplicaCount: 1
          ingress:
            enabled: true

        argocd:
          installCRDs: false
          global:
            image:
              tag: v2.1.3
          dex:
            enabled: false
          server:
            ingress:
              enabled: true
              https: true
            config:
              repositories: |
                - type: helm
                  name: stable
                  url: https://charts.helm.sh/stable
                - type: helm
                  name: argo-cd
                  url: https://argoproj.github.io/argo-helm

        externaldns:
          enabled: "{{ hostvars.localhost.iac.argocd.dns.enabled|default('false') }}"
          rfc2136:
            host: "{{ hostvars.localhost.iac.argocd.dns.host|default() }}"
            zone: "{{ hostvars.localhost.iac.argocd.dns.zone|default() }}"
            tsigSecret: "{{ hostvars.localhost.iac.argocd.dns.secret|default() }}"

        metallb:
          pools:
          - name: default
            protocol: layer2
            addresses:
            - "{{ hostvars.localhost.iac.argocd.metallb.addresses|default(ansible_host + '-' + ansible_host) }}"
            avoid-buggy-ips: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
