apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaboom-games-main
  namespace: argocd
spec:
  destination:
    namespace: kaboom-games
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/kube-apps'
    targetRevision: HEAD
    path: 'kaboom-games'
    helm:
      values: |
        website: kaboom-games
        domain: "{{ hostvars.localhost.iac.name }}.{{ hostvars.localhost.iac.domain|default('example.com') }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
