apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-main
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/toleksa/kube-apps'
    targetRevision: HEAD
    path: 'wordpress'
    helm:
      values: |
        website: wordpress
        domain: "{{ hostvars.localhost.iac.name }}.{{ hostvars.localhost.iac.domain|default(default.iac.domain) }}"
        adminPassword: password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
