---
- block:
  - name: create project dir
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ terraform_tmp_path }}/{{ instance.key }}"

  - name: copy terraform manifest
    template:
      src: "{{ item }}"
      dest: "{{ terraform_tmp_path }}/{{ instance.key }}/{{ item }}"
    with_items:
    - vm.tf

  - name: apply terraform
    terraform:
      binary_path: "{{ terraform_path }}"
      project_path: "{{ terraform_tmp_path }}/{{ instance.key }}"
      force_init: true

  delegate_to: localhost
