---
# tasks file for argocd

- ansible.builtin.include_role: 
    name: rke2

- name: Waiting for kubernetes to start
  ansible.builtin.shell: >
    until kubectl get nodes | grep -i `hostname` | grep " Ready " ; do
      sleep 5s
      echo -n .
    done
  changed_when: false
  when: "'rke2-worker' not in group_names"

- include_tasks: install.yaml
  when: "'rke2-worker' not in group_names"

