---
- hosts: "{{ variable_host }}"
  gather_facts: no
  tasks:
  - name: debug
    debug:
      var: terraform_action
  - name: show iac
    debug:
      var: iac
  - name: manager instance
    include_role:
      name: "{{ instance.value.provider.name }}"
    loop: "{{ iac.hosts|dict2items }}"
    loop_control:
      label: 'to jest label {{ instance.key }}'
      loop_var: instance
  - meta: refresh_inventory

- hosts: base
  roles:
  - base
 
- hosts: rke2
  roles:
  - rke2

