---
- hosts: "{{ variable_host }}"
  gather_facts: no
  tasks:
  - name: debug
    debug:
      var: terraform_action
  - name: show iac
    debug:
      var: iac
  - name: manager instance
    include_role:
      name: "{{ instance.value.provider.name }}"
    loop: "{{ iac.hosts|dict2items }}"
    loop_control:
      label: 'to jest label {{ instance.key }}'
      loop_var: instance

- hosts: all
  gather_facts: no
  tasks:
  - meta: refresh_inventory

  - name: print inventory
    debug:
      var: hostvars | list
    run_once: true

#  - name: stop here after terraform destroy
#    fail:
#      msg: "stop here after terraform destroy"
#    when: terraform_action == "destroy"

#  - meta: end_batch
#    when: terraform_action == "destroy"

- hosts: base
  roles:
  - base
 
- hosts: rke2
  roles:
  - rke2

- hosts: argocd
  roles:
  - argocd

