---
- hosts: "{{ variable_host }}"
  gather_facts: no
  tasks:
  - name: call terraform
    include_role: 
      name: "{{ iac.providers[0].type }}"
      #TODO: hardcoded
      #name: "libvirt"
    #when: iac.providers[0].type == "libvirt"

#- import_playbook: install.yaml
#  when: terraform_action != 'destroy'
