iac:
  name: "default"
  #domain: "kube.ac"
  providers:
  - name: "ivy"
    type: "libvirt"
    config: "qemu+ssh://root@192.168.0.3/system"
  hosts:
    machine:
      #provider:
        #name: ivy
      networks:                                                                          
      #- name: "main"
      - bridge: "br0"
      #count: 1
      #roles:
      #- base
      #resources:
      #  cpu: 1
      #  mem: 1000
