iac:
  name: "c6"
  domain: "kube.ac"
  message: "happy hyper-v'ing :)"
  providers:
  - name: "hyperv"
    type: "hyperv"
  argocd:
    targetRevision: HEAD
    k8s_backend: rke2
    dns:
      enabled: true
      host: 192.168.0.2
      zone: "kube.ac"
      secret: "{{ lookup('ansible.builtin.env', 'DNS_KEY')|default() }}"
    kubecost:
      enabled: true
    longhorn:
      enabled: true
    metallb:
      enabled: true
    monitoring:
      enabled: true
    neuvector:
      enabled: true
    elk:
      enabled: false
    istio:
      enabled: false
    apps:
    #- kaboom-games-main.yaml
    - python-rest-api-main.yaml
    #- wordpress-main.yaml
    #- argo-combined-app.yaml
  hosts:
    s:
      count: 1
      roles:
      - argocd
      #- kubernetes-tools
      #- base
      provider:
        name: hyperv
      disks:
      - name: "root"
        size: "53687091200"
#        pool: "default"
#        base_volume: "ubuntu-jammy"
      networks:
##      - name: "main"
#      - bridge: "br0"
        mac_prefix: "DEAD010601"
      resources:
        cpu: 4
        mem: 10000

