libvirt:
  config:
    source: "dmacvicar/libvirt"
    version: "0.6.12"

iac:
  name: "oci"
  domain: "kube.ac"
  providers:
  - name: "ivy"
    type: "oci"
    config: "~/.oci/config"
  pools:
  - name: "default"
    path: "/virtualki"
#  networks:
#  - name: "main"
#    bridge: "br0"
  volumes:
  - name: ubuntu-jammy
    source: "http://192.168.0.2:8765/jammy-server-cloudimg-amd64-disk-kvm.img"
    format: "qcow2"
    pool: "default"
  argocd:
    #k8s_backend: k3s
    dns:
      #enabled: false
      #host: 127.0.0.1
      #zone: "example.com"
      #secret: "secret"
      enabled: true
      host: 192.168.0.2
      zone: "kube.ac"
      secret: "{{ lookup('ansible.builtin.env', 'DNS_KEY')|default() }}"
      metrics: true
    metallb:
      #addresses: "192.168.0.231-192.168.0.239"
    monitoring:
      enabled: true
    elk:
      enabled: false
    istio:
      enabled: false
    apps:
    #- kaboom-games-main.yaml
    - python-rest-api-main.yaml
    #- wordpress-main.yaml
    #- argo-combined-app.yaml
  rke2:
    join_token: ivy-123456
  k3s:
    join_token: ivy-123456
  hosts:
    oci:  #TODO: hardcoded name in deploy.yaml
      count: 1
      roles:
      #- argocd
      #- rke2
      - k3s
      #- base
      provider:
        name: ivy
      disks:
      - name: "root"
        size: "103687091200"
        pool: "default"
        base_volume: "ubuntu-jammy"
      networks:
#     - name: "main"
      - bridge: "br0"
        mac_prefix: "de:ad:01:00:03"
      resources:
        cpu: 6
        #mem: 14500
        mem: 10000

