---
- name: compress-table
  hosts: postgres

  tasks:
  - name: create extension main
    command: psql -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"
    become_user: postgres
    become_method: su
    become: true
    when: "'1' in inventory_hostname"

  - name: create table
    command: psql -c "CREATE TABLE IF NOT EXISTS compress (id VARCHAR(20) PRIMARY KEY, num VARCHAR(20), data VARCHAR(20), time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);" -d test1
    become_user: postgres
    become_method: su
    become: true
    when: "'1' in inventory_hostname"

  - name: create hypertable
    command: psql -c "SELECT create_hypertable('compress','id',chunk_time_interval => 600);" -d test1
    become_user: postgres
    become_method: su
    become: true
    when: "'1' in inventory_hostname"

  - name: compress-table
    command: psql -c "ALTER TABLE compress SET (timescaledb.compress, timescaledb.compress_segmentby = 'time, data, num', timescaledb.compress_orderby = 'id');" -d test1
    become_user: postgres
    become_method: su
    become: true
    register: create_result
    when: "'1' in inventory_hostname"

  - name: print result
    debug:
      msg: "{{ create_result.stdout }}"
    when: "'1' in inventory_hostname"

