---
- name: install postgres
  hosts: postgres

  tasks:

#  - name: stop and disable firewalld
#    systemd:
#      name: firewalld
#      state: stopped
#      enabled: no

  - name: install postgres repo
    dnf:
      name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
      state: present
      disable_gpg_check: yes

  - name: timescaledb repo
    shell: curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.rpm.sh | bash

  - name: disable default postgres
    command: dnf -qy module disable postgresql

  - name: install postgres and timescaledb packages - v11
    dnf:
      name:
        - timescaledb-postgresql-11
        - timescaledb-loader-postgresql-11-1.7.5
        - postgresql11-devel 
        - postgresql11-contrib
      state: latest

  - name: postgres remote_tmp dir
    file:
      path: /var/lib/pgsql/.ansible/tmp/
      mode: '0700'
      owner: postgres
      group: postgres
      state: directory

  - name: .ssh dir
    file:
      path: '~/.ssh'
      mode: '0700'
      state: directory
    become: true
    become_user: postgres
    become_method: su

  - name: ssh keys
    get_url:
      url: 'http://192.168.0.2:8765/ssh/postgres/{{ item }}'
      dest: '~/.ssh/{{ item }}'
      mode: '0600'
    with_items:
    - 'id_rsa'
    - 'id_rsa.pub'
    - 'authorized_keys'
    become: true
    become_user: postgres
    become_method: su

  - name: postgres initdb
    command: /usr/pgsql-11/bin/postgresql-11-setup initdb
    when: "'1' in inventory_hostname"

  - name: postgresql.conf - listen_address
    lineinfile:
      dest: /var/lib/pgsql/11/data/postgresql.conf
      regexp: 'listen_addresses ='
      line: "listen_addresses = '*'"
    when: "'1' in inventory_hostname"

  - name: postgresql.conf - shared_preload_libraries
    lineinfile:
      dest: /var/lib/pgsql/11/data/postgresql.conf
      regexp: 'shared_preload_libraries'
      line: "shared_preload_libraries = 'timescaledb'"
    when: "'1' in inventory_hostname"

  - name: enable and start postgres
    systemd:
      name: postgresql-11
      state: started
      enabled: yes
    when: "'1' in inventory_hostname"

  - name: psql PATH
    lineinfile:
      path: /var/lib/pgsql/.bash_profile
      line: export PATH=$PATH:/usr/pgsql-11/bin/



