---
- name: stop-and-reset
  hosts: postgres

  tasks:
  - name: Populate service facts
    service_facts:

  - name: stop postgresql-11
    systemd:
      name: postgresql-11
      state: stopped
    when: "'postgresql-11.service' in services"

  - name: stop postgresql-12
    systemd:
      name: postgresql-12
      state: stopped
    when: "'postgresql-12.service' in services"

  - name: clear data
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
    - /var/lib/pgsql/11/data
    - /var/lib/pgsql/12/data

  - name: restore .bash_profile
    copy:
      dest: ~/.bash_profile
      content: |
        [ -f /etc/profile ] && source /etc/profile
        PGDATA=/var/lib/pgsql/11/data
        export PGDATA
        # If you want to customize your settings,
        # Use the file below. This is not overridden
        # by the RPMS.
        [ -f /var/lib/pgsql/.pgsql_profile ] && source /var/lib/pgsql/.pgsql_profile
        export PATH=$PATH:/usr/pgsql-11/bin/
    become_user: postgres
    become_method: su
    become: true

