---
- hosts: hyperv
  gather_facts: no
  tasks:
  - name: call terraform
    include_role:
      name: "{{ iac.providers[0].type }}"
      #TODO: hardcoded
      #name: "libvirt"
    #when: iac.providers[0].type == "libvirt"
- hosts: all
  gather_facts: false
  tasks:
  - name: print inventory
    debug:
      var: hostvars | list
    run_once: true
  - name: Wait for machine
    ansible.builtin.wait_for_connection:
      #default values:
      #delay: 0
      #sleep: 1
      #timeout: 600

- hosts: base
  roles:
  - base

- hosts: kubernetes-tools
  roles:
  - kubernetes-tools

- hosts: elkstack
  roles:
  - elkstack

- hosts: k3s
  roles:
  - k3s

- hosts: rke2
  roles:
  - rke2

- hosts: argocd
  roles:
  - argocd

- hosts: openshift
  roles:
  - openshift

- hosts: localhost
  tasks:
  - name: print message
    ansible.builtin.debug:
      msg: "{{ iac.message }}"
    when: iac.message is defined

