---
- hosts: all
  gather_facts: false
  tasks:
  - name: print inventory
    debug:
      var: hostvars | list
    run_once: true
  - name: Wait for machine
    ansible.builtin.wait_for_connection:
      #default values:
      #delay: 0
      #sleep: 1
      #timeout: 600
- hosts: all
  roles:
  - base

