---
- hosts: server
  tasks:
  - name: whoami
    ansible.builtin.shell: whoami
    register: whoami
  - name: print
    debug:
      msg: "{{ whoami.stdout }}"

- hosts: worker
  tasks:
  - name: id
    ansible.builtin.shell: id
    register: id
  - name: print
    debug:
      msg: "{{ id.stdout }}"

- hosts: all
  tasks:
  - name: install python3
    ansible.builtin.apt:
      name: python3
      state: present

