---
- block:
  - name: destroy
    terraform:
      binary_path: "{{ terraform_path }}"
      project_path: "{{ storage_path }}/{{ iac.name }}/terraform"
      state: absent

#  - meta: end_play

  delegate_to: localhost
