---
- block:
  - name: create project dir
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ storage_path }}/{{ iac.name }}/terraform"

  - name: copy terraform manifest
    template:
      src: "{{ item }}"
      dest: "{{ storage_path }}/{{ iac.name }}/terraform/{{ instance.key }}.tf"
    with_items:
    - vm.tf

  - name: apply terraform
    terraform:
      binary_path: "{{ terraform_path }}"
      project_path: "{{ storage_path }}/{{ iac.name }}/terraform"
      force_init: true

  delegate_to: localhost
