libvirt:
  config:
    source: "dmacvicar/libvirt"
    version: "0.6.12"

iac:
  name: "c0"
  domain: "kube.ac"
  providers:
  - name: "libvirt"
    config: "qemu+ssh://root@192.168.0.4/system"
  pools:
  - name: "default"
    path: "/default"
#  - name: "test"
#    path: "/tmp/somewhere"
#  - name: "test2"
#    path: "/tmp/somewhere2"
  networks:
  - name: "default"
    bridge: "default"
  - name: "net1"
    bridge: "br0"
#  - name: "net2"
#    bridge: "br0"
  volumes:
  - name: ubuntu-jammy
    source: "http://192.168.0.2:8765/jammy-server-cloudimg-amd64-disk-kvm.img"
    format: "qcow2"
    pool: "default"
  hosts:
    simple_vm:
      count: 1
      provider:
        name: libvirt
      disks:
      - name: "root"
        size: "53687091200"
        pool: "default"
        base_volume: "ubuntu-jammy"
#      - name: "home"
#        pool: "default"
#        source: "http://192.168.0.2:8765/jammy-server-cloudimg-amd64-disk-kvm.img"
      networks:
      - name: "default"
        mac_prefix: "44:00:00:00:00"
      resources:
        cpu: 2
        mem: 2048
      user_data_pool: "default"
      user_data:
        prefer_fqdn_over_hostname: true
        ssh_pwauth: True
        chpasswd:
          list: root:root
          expire: False

        users:
          - name: root
            ssh_import_id:
              - gh:toleksa

        final_message: |
          cloud-init has finished
          version: $version
          timestamp: $timestamp
          datasource: $datasource
          uptime: $uptime

        packages:
          - qemu-guest-agent

        runcmd:
          - echo "starting user_data_base"
          - systemctl start qemu-guest-agent
          - curl http://192.168.0.2:8765/dns-update.sh > /etc/cron.hourly/dns-update.sh
          - chmod +x /etc/cron.hourly/dns-update.sh
          - /etc/cron.hourly/dns-update.sh
          - export HOME=/root ; cd
          - echo "tail -f /var/log/cloud-init-output.log -n +0" >> ~/.bash_history
          - if [ -d /etc/update-motd.d ]; then chmod -x /etc/update-motd.d/* ; fi
          - sed -i 's/#UseDNS no/UseDNS no/' /etc/ssh/sshd_config ; systemctl restart ssh*
          - printf "nameserver 192.168.0.2" > /etc/resolv.conf
          - if [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ]; then chattr +i /etc/resolv.conf ; fi
          - printf "[Resolve]\nDNS=192.168.0.2" > /etc/systemd/resolved.conf
          - systemctl restart systemd-resolved
          - printf "Host *\nStrictHostKeyChecking no" > /etc/ssh/ssh_config.d/99-disable-strict-checking.conf
          - sed -i 's/return/echo ""/' /root/.bashrc
          - timedatectl set-timezone Europe/Zurich
          - if [ -f /usr/bin/apt ]; then apt install atop python-is-python3 ; fi
          - echo "finished user_data_base" | tee /cloud-init-base-ready.txt

