---
- name: Ensure ulimit is set to 1048576
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^.*soft nofile.*$'
    line: 'root soft nofile 1048576'

- name: Ensure ulimit is set to 1048576
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^.*hard nofile.*$'
    line: 'root hard nofile 1048576'

- name: Setting-up file-max limit
  sysctl:
    name: fs.file-max
    value: 1048576
    state: present
    reload: yes

- name: install packages
  ansible.builtin.apt:
    pkg:
    - qemu-guest-agent
    - vim
    - bind9-utils
    - atop
    - python-is-python3
    state: present

- name: start and enable qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: yes

- name: create /etc/cron.hourly
  ansible.builtin.file:
    path: /etc/cron.hourly
    state: directory
    mode: '0755'

- name: get dns-update.sh
  ansible.builtin.get_url:
    url: 'http://192.168.0.2:8765/dns-update.sh'
    dest: '/etc/cron.hourly/dns-update.sh'
    mode: '0700'
  notify: update dns
- name: crontab dns-update
  ansible.builtin.cron:
    name: dns-update.sh
    special_time: reboot
    job: '/etc/cron.hourly/dns-update.sh'

- name: Set timezone to Europe/Zurich
  community.general.timezone:
    name: Europe/Zurich

- name: set dns
  ansible.builtin.lineinfile:
    dest: /etc/systemd/resolved.conf
    line: "DNS=192.168.0.2"
    regexp: "DNS="
    state: present
  notify: restart resolved

- name: .bash_profile
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/toleksa/configs/main/.bash_profile'
    dest: '/root/.bash_profile'
    mode: '0700'
- name: .bashrc
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/toleksa/configs/main/.bashrc'
    dest: '/root/.bashrc'
    mode: '0700'
- name: .vimrc
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/toleksa/configs/main/.vimrc'
    dest: '/root/.vimrc'
    mode: '0700'

- name: remove /etc/update-motd.d/
  ansible.builtin.file:
    path: /etc/update-motd.d/
    state: absent

- meta: flush_handlers
